version: '3.8'
services:
    #PHP Service
    app: &app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
        depends_on:
            - db
            - redis

    #Startup Service
    startup:
        <<: *app
        restart: on-failure
        command:
            - /bin/sh
            - -c
            - |
                composer install
                php artisan migrate

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www:delegated
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
        depends_on:
            startup:
                condition: service_completed_successfully

    #PostgreSQL Service
    db:
        image: postgres:latest
        container_name: db
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/postgresql/data:delegated
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
            PGDATA: /var/lib/postgresql/data
        networks:
            - app-network

    #Redis Service
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        sysctls:
            - net.core.somaxconn=511
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data:delegated
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    db-data:
        driver: local
    redis-data:
        driver: local
